name: Python
channels:
  - conda-forge
dependencies:
  - python=3.9
  - bokeh
  - cartopy
  - eofs
  - erddapy
  - folium
  - geopandas
  - holoviews
  - hvplot
  - iris
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - sympy
  - utide
  - windrose
  - xarray
  - xlrd
  # R packages.
  - rpy2
  - r-base=4
  - r-dt
  - r-finch
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-obistools
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-robis>=2.3.9
  - r-sp
  - r-xtractomatic
  - r-xts
